# Generated by Django 4.1.3 on 2023-04-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_system', '0002_alter_adminmonthlyfavourites_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='media/bookImages/'),
        ),
    ]
