# Generated by Django 4.1.3 on 2023-04-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_system', '0004_book_library_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_library',
            name='private',
        ),
        migrations.AddField(
            model_name='library',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
